
import { Property, PropertyStatus, UserRole, FraudSignal } from './types';

export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'Luxury 5-Bedroom Detached Duplex',
    address: 'Banana Island, Ikoyi, Lagos',
    price: 450000000,
    status: PropertyStatus.AVAILABLE,
    type: 'Sale',
    ownerId: 'user-landlord-1',
    ownerName: 'Chief Adebayo',
    ownerPhone: '+2348012345678',
    ownerAddress: '12 Luxury Lane, Ikoyi, Lagos',
    ownerKycStatus: true,
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800'],
    description: 'Ultra-modern luxury living in the heart of Africa\'s most exclusive neighborhood. Features include 24/7 security, smart home automation, and a private pool.',
    upc: 'UPC-LA-BI-001',
    fraudScore: 5,
    signals: [],
  },
  {
    id: 'prop-2',
    title: 'Executive 3-Bedroom Apartment',
    address: 'Maitama, Abuja (FCT)',
    price: 8500000,
    status: PropertyStatus.PENDING_CONFIRMATION,
    type: 'Rent',
    ownerId: 'user-landlord-1',
    ownerName: 'Chief Adebayo',
    ownerPhone: '+2348012345678',
    ownerAddress: '12 Luxury Lane, Ikoyi, Lagos',
    ownerKycStatus: true,
    tenantId: 'user-tenant-1',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800'],
    description: 'Exquisitely finished apartment in a serene environment. Highly secured with armed guards and biometric access control.',
    upc: 'UPC-AB-MT-042',
    fraudScore: 12,
    signals: [],
  },
  {
    id: 'prop-3',
    title: 'Commercial Office Space',
    address: 'Victoria Island, Lagos',
    price: 250000000,
    status: PropertyStatus.LOCKED,
    type: 'Sale',
    ownerId: 'user-landlord-2',
    ownerName: 'V.I. Holdings Ltd',
    ownerPhone: '+23415550199',
    ownerAddress: 'Tower 4, VI, Lagos',
    ownerKycStatus: false,
    images: ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800'],
    description: 'Prime commercial location for headquarters. Currently locked due to conflicting ownership documents.',
    upc: 'UPC-LA-VI-210',
    fraudScore: 88,
    signals: [
      {
        id: 'sig-1',
        type: 'IP',
        severity: 'High',
        description: 'Listing attempted from high-risk VPN IP range.',
        timestamp: new Date().toISOString()
      },
      {
        id: 'sig-2',
        type: 'Document',
        severity: 'Medium',
        description: 'Property document hash matches existing record (UPC-LA-VI-210).',
        timestamp: new Date().toISOString()
      }
    ],
    documentHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
  },
  {
    id: 'prop-4',
    title: 'Serviced 2-Bedroom Flat',
    address: 'GRA, Port Harcourt, Rivers',
    price: 3500000,
    status: PropertyStatus.SOLD,
    type: 'Rent',
    ownerId: 'user-landlord-3',
    ownerName: 'Dr. Stella Okoro',
    ownerPhone: '+2348123456789',
    ownerAddress: '5 Garden City Ave, Port Harcourt',
    ownerKycStatus: true,
    tenantId: 'user-tenant-2',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800'],
    description: 'Fully serviced flat with constant power supply and top-notch security features.',
    upc: 'UPC-RI-PH-012',
    fraudScore: 2,
    signals: [],
  },
  {
    id: 'prop-5',
    title: 'Modern 4-Bedroom Terrace House',
    address: 'Lekki Phase 1, Lagos',
    price: 120000000,
    status: PropertyStatus.AVAILABLE,
    type: 'Sale',
    ownerId: 'user-landlord-1',
    ownerName: 'Chief Adebayo',
    ownerPhone: '+2348012345678',
    ownerAddress: '12 Luxury Lane, Ikoyi, Lagos',
    ownerKycStatus: true,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800'],
    description: 'Contemporary design in a gated community. Features a fitted kitchen, all en-suite rooms, and a Boy\'s Quarter (BQ). Perfect for young families.',
    upc: 'UPC-LA-LK-088',
    fraudScore: 8,
    signals: [],
  },
  {
    id: 'prop-6',
    title: 'Cozy 3-Bedroom Apartment',
    address: 'Gwarinpa, Abuja',
    price: 3500000,
    status: PropertyStatus.RENTED,
    type: 'Rent',
    ownerId: 'user-landlord-2',
    ownerName: 'V.I. Holdings Ltd',
    ownerPhone: '+23415550199',
    ownerAddress: 'Tower 4, VI, Lagos',
    ownerKycStatus: true,
    tenantId: 'user-tenant-1',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800'],
    description: 'Well-maintained apartment in the largest housing estate in West Africa. Close to markets and major transport routes.',
    upc: 'UPC-AB-GW-115',
    fraudScore: 4,
    signals: [],
  },
  {
    id: 'prop-7',
    title: 'Grand 5-Bedroom Detached House with BQ',
    address: 'Old Ikoyi, Lagos',
    price: 650000000,
    status: PropertyStatus.AVAILABLE,
    type: 'Sale',
    ownerId: 'user-landlord-1',
    ownerName: 'Chief Adebayo',
    ownerPhone: '+2348012345678',
    ownerAddress: '12 Luxury Lane, Ikoyi, Lagos',
    ownerKycStatus: true,
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800'],
    description: 'A masterpiece of classic architecture. Set on a massive plot of land with lush greenery, high ceilings, and premium wood finishings.',
    upc: 'UPC-LA-IK-202',
    fraudScore: 2,
    signals: [],
  },
  {
    id: 'prop-8',
    title: 'Charming 4-Bedroom Bungalow',
    address: 'Independence Layout, Enugu',
    price: 45000000,
    status: PropertyStatus.AVAILABLE,
    type: 'Sale',
    ownerId: 'user-landlord-3',
    ownerName: 'Dr. Stella Okoro',
    ownerPhone: '+2348123456789',
    ownerAddress: '5 Garden City Ave, Port Harcourt',
    ownerKycStatus: true,
    images: ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800'],
    description: 'Classic bungalow in the coal city. Very spacious compound, fully fenced with electric wires. Excellent choice for retirement or a quiet family life.',
    upc: 'UPC-EN-IL-009',
    fraudScore: 1,
    signals: [],
  },
  {
    id: 'prop-9',
    title: 'Luxury 6-Bedroom Mansion',
    address: 'Nassarawa GRA, Kano',
    price: 180000000,
    status: PropertyStatus.AVAILABLE,
    type: 'Sale',
    ownerId: 'user-landlord-2',
    ownerName: 'V.I. Holdings Ltd',
    ownerPhone: '+23415550199',
    ownerAddress: 'Tower 4, VI, Lagos',
    ownerKycStatus: true,
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800'],
    description: 'Exquisite mansion in the most prestigious part of Kano. Features traditional architectural elements combined with modern luxury.',
    upc: 'UPC-KN-NS-055',
    fraudScore: 6,
    signals: [],
  },
  {
    id: 'prop-10',
    title: 'Fully Serviced 3-Bedroom Flat',
    address: 'Ikeja GRA, Lagos',
    price: 5500000,
    status: PropertyStatus.AVAILABLE,
    type: 'Rent',
    ownerId: 'user-landlord-1',
    ownerName: 'Chief Adebayo',
    ownerPhone: '+2348012345678',
    ownerAddress: '12 Luxury Lane, Ikoyi, Lagos',
    ownerKycStatus: true,
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800'],
    description: 'Top-tier apartment in the heart of Ikeja. 24/7 power, industrial water treatment, and proximity to the airport and major business hubs.',
    upc: 'UPC-LA-IG-332',
    fraudScore: 3,
    signals: [],
  }
];
