
import { GoogleGenAI, Modality } from "@google/genai";

// Initialize the Gemini API client with the environment API key
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Verify an address in Nigeria using Google Maps grounding.
 * Per guidelines, maps grounding is supported in Gemini 2.5 series.
 */
export const validateAddressWithMaps = async (address: string) => {
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: `Verify this address in Nigeria: ${address}. Provide a clean, standardized version of the address and confirm if it exists.`,
    config: {
      tools: [{ googleMaps: {} }]
    }
  });

  return {
    standardized: response.text || address,
    sources: response.candidates?.[0]?.groundingMetadata?.groundingChunks || []
  };
};

/**
 * Retrieve neighborhood insights using Google Maps grounding.
 * Gemini 2.5 Flash is recommended for low-latency grounding tasks.
 */
export const getNeighborhoodInsights = async (address: string, lat?: number, lng?: number) => {
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: `What are the nearby amenities, schools, and essential facilities for a property at ${address}? Provide a concise summary.`,
    config: {
      tools: [{ googleMaps: {} }],
      toolConfig: {
        retrievalConfig: {
          latLng: lat && lng ? { latitude: lat, longitude: lng } : undefined
        }
      }
    }
  });

  const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks
    ?.map((chunk: any) => chunk.maps ? { title: chunk.maps.title, uri: chunk.maps.uri } : null)
    .filter(Boolean) || [];

  return {
    text: response.text || "No insights found.",
    sources
  };
};

// Generate a professional property listing description using Gemini 3 Flash (optimized for text)
export const generatePropertyListingDescription = async (details: string) => {
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: `Write a high-end Nigerian real estate listing description based on these details: ${details}. Use terms like 'BQ', 'Duplex' appropriately. Highlight security and verification aspects.`,
  });
  return response.text || "Failed to generate description.";
};

// Analyze fraud signals using Gemini 3 Pro (optimized for complex reasoning and audit)
export const analyzeFraudLog = async (signals: any[], address: string) => {
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-preview',
    contents: `Analyze these security signals for a property at ${address}: ${JSON.stringify(signals)}. Provide a detailed risk assessment report. Identify potential red flags, suspicious patterns, and suggest whether the listing should remain active or be locked for manual review.`,
  });
  return {
    text: response.text || "No analysis generated by AI analyst."
  };
};

// Generate high-quality speech for property descriptions using Gemini TTS
export const generatePropertyAudio = async (text: string) => {
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-preview-tts",
    contents: [{ parts: [{ text: `Say clearly and professionally: ${text}` }] }],
    config: {
      responseModalities: [Modality.AUDIO],
      speechConfig: {
        voiceConfig: {
          prebuiltVoiceConfig: { voiceName: 'Kore' },
        },
      },
    },
  });

  const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
  return base64Audio;
};

// Manually implement base64 decoding for raw PCM audio data (required by guidelines)
export const decodeBase64 = (base64: string) => {
  const binaryString = atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
};

// Decode raw PCM audio data into an AudioBuffer for browser playback
export async function decodeAudioData(
  data: Uint8Array,
  ctx: AudioContext,
  sampleRate: number,
  numChannels: number,
): Promise<AudioBuffer> {
  const dataInt16 = new Int16Array(data.buffer);
  const frameCount = dataInt16.length / numChannels;
  const buffer = ctx.createBuffer(numChannels, frameCount, sampleRate);

  for (let channel = 0; channel < numChannels; channel++) {
    const channelData = buffer.getChannelData(channel);
    for (let i = 0; i < frameCount; i++) {
      channelData[i] = dataInt16[i * numChannels + channel] / 32768.0;
    }
  }
  return buffer;
}
